### PR TITLE
[FIX] Fix for exclude bug

### PR DESCRIPTION
**Pull request by abhinavvaidya90**
https://github.com/rheinwerk-verlag/postgresql-anonymizer/issues/14

### CODE REVIEW

**Review by abhinavvaidya90 — COMMENTED** [review]
I have made the fix and tested on Python 3.6 running on Ubuntu 18.04 system and the error is resolved.

**Comment by abhinavvaidya90** [comment]
@rheinwerk-mp @hkage  : could you please check the PR ?

**Comment by hkage** [comment]
Thanks for your pull request! I will take a look as soon as possible.

**Comment by hkage** [comment]
Looks good to me. Thanks for your contribution and the error details.

**Pull request merged**
