### PR TITLE
[FEATURE] Specify (SQL WHERE) search_condition, to filter the table for rows to be anonymized.

### PR DESCRIPTION
**Pull request by bobslee**

### CODE REVIEW

**Comment by bobslee** [comment]
@hkage please could you review my PR ? I really need to get this on PyPi.
Great tool by the way! Thanks!

**Comment by hkage** [comment]
Thanks for your PR @bobslee This is a great idea to narrow down the data that should be anonymized. I will take a look into all open pull requests today and make a new release if everything looks ok.

**Comment by hkage** [comment]
Looks good to me.

**Comment by bobslee** [comment]
Thanks @hkage

**Comment by bobslee** [comment]
@hkage It seems my PR broke the docs TOC / index, see screenshot.
How to fix?

image

**Comment by hkage** [comment]
It seems like the code snippet had broken the TOC, but I don't know exactly why. I added a sub-section for all elements before the "Provider" section (https://github.com/rheinwerk-verlag/postgresql-anonymizer/commit/b22cdfc80bf0357d0155ebdffa262a4f36dbe8e8#diff-7803db48064b8857ffa23bfa8cad7b59d218e9cc842f1b165551388118c30ac2R4) and the TOC seems to be correct.

The docs will be updated with the next release, I cannot re-upload the same version again on PyPi.

**Pull request merged**
